---
title: "ADNI 1 GWAS QC"
author: "Shea Andrews"
date: "`r Sys.Date()`"
editor_options:
  chunk_output_type: console
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
params:
  cohort: 'ADNI_1'
  path.wd: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/1_RawData/ADNI_1/'
  file.name: 'ADNI_1_hg19'
  path.sex.file: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1.sexcheck'
  path.het.file: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_04_het.het'
  path.genome.file: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_03_IBD.genome'
  path.fam.file: '~/Dropbox/Research/PostDoc/MitoWax/2_Derived_Data/GWAS_pres_processing/ADNI_1/ADNI1_01.fam'
  path.eigenvec: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/merged_1000_adni_clust.eigenvec'
  path.eigenval: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/merged_1000_adni_clust.eigenval'
  path.base_pops: '~/Dropbox/Research/PostDoc/MitoWax/2_Derived_Data/GWAS_pres_processing/20130606_g1k.ped'
  path.target_pops: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_05_thined.fam'
  path.ps.eigenvec: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI_clust.eigenvec'
  path.ps.eigenval: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI_clust.eigenval'
  path.irem.fail: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_02.irem'
  path.het.fail: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_exclude.heterozigosity'
  path.sex.fail: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_exclude.sexcheck'
  path.pca.fail: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_exclude.pca'
  path.rel.fail: '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/2_DerivedData/ADNI_1/ADNI1_exclude.relatedness'
---

```{r child = '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/3_Scripts/GWAS_QC/markdown/call_rates.Rmd'}
```

```{r child = '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/3_Scripts/GWAS_QC/markdown/sexcheck_QC.Rmd'}
```

```{r child = '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/3_Scripts/GWAS_QC/markdown/Heterozygosity_QC.Rmd'}
```

```{r child = '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/3_Scripts/GWAS_QC/markdown/relatedness_QC.Rmd'}
```

```{r child = '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/3_Scripts/GWAS_QC/markdown/PCA_QC.Rmd'}
```

```{r child = '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/3_Scripts/GWAS_QC/markdown/population_stratification_QC.Rmd'}
```

```{r child = '~/Dropbox/Research/PostDoc-MSSM/3_mitoWAX/3_Scripts/GWAS_QC/markdown/Sample_QC.Rmd'}
```
