
message("Render Final Report",
        "\n markdown: ", paste0("workflow/scripts/", snakemake@params[["script"]]),
        "\n SexFile: ", snakemake@input[["SexFile"]],
        "\n hwe: ", snakemake@input[["hwe"]],
        "\n frq: ", snakemake@input[["frq"]],
        "\n frqx: ", snakemake@input[["frqx"]],
        "\n imiss: ", snakemake@input[["imiss"]],
        "\n HetFile: ", snakemake@input[["HetFile"]],
        "\n IBD_stats: ", snakemake@input[["IBD_stats"]],
        "\n PCA_rdat: ", snakemake@input[["PCA_rdat"]],
        "\n PopStrat_eigenval: ", snakemake@input[["PopStrat_eigenval"]],
        "\n PopStrat_eigenvec: ", snakemake@input[["PopStrat_eigenvec"]],
        "\n partmethod: ", snakemake@input[["partmethod"]],
        "\n output: ", snakemake@output[[1]],
        "\n rwd: ", snakemake@params[["rwd"]],
        "\n Family: ", snakemake@params[["Family"]],
        "\n pi_threshold: ", snakemake@params[["pi_threshold"]],
        "\n output_dir: ", snakemake@params[["output_dir"]],
        "\n geno_miss: ", snakemake@params[["geno_miss"]],
        "\n MAF: ", snakemake@params[["MAF"]],
        "\n HWE: ", snakemake@params[["HWE"]],
        "\n superpop: ", snakemake@params[["superpop"]],
        "\n partmethod: ", snakemake@params[["partmethod"]]
      )

rmarkdown::render(
  input = paste0("workflow/scripts/", snakemake@params[["script"]]),
  clean = TRUE,
  intermediates_dir = snakemake@params[["idir"]],
  output_file = snakemake@output[[1]],
  output_dir = snakemake@params[["output_dir"]],
  output_format = "all",
  params = list(
    rwd = snakemake@params[["rwd"]],
    Sample = snakemake@wildcards[["sample"]],
    # DataIn = snakemake@xxx[[xxx]],
    Path_hwe = snakemake@input[["hwe"]],
    Path_frq = snakemake@input[["frq"]],
    Path_frqx = snakemake@input[["frqx"]],
    Path_imiss = snakemake@input[["imiss"]],
    Path_SexFile = snakemake@input[["SexFile"]],
    Path_HetFile = snakemake@input[["HetFile"]],
    Family = snakemake@params[["Family"]],
    Path_IBD_stats = snakemake@input[["IBD_stats"]],
    pi_threshold = snakemake@params[["pi_theshold"]],
    Path_PCA_rdat = snakemake@input[["PCA_rdat"]],
    Path_PopStrat_eigenvec = snakemake@input[["PopStrat_eigenvec"]],
    Path_PopStrat_eigenval = snakemake@input[["PopStrat_eigenval"]],
    auth = "Shea J. Andrews and Brian Fulton-Howard",
    maf = snakemake@params[["MAF"]],
    missing_geno = snakemake@params[["geno_miss"]],
    missing_sample = snakemake@params[["samp_miss"]],
    hwe = snakemake@params[["HWE"]],
    superpop = snakemake@params[["superpop"]],
    partmethod = snakemake@params[["partmethod"]]
  )
)
